Modules/Admin/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Admin\Http\Middleware\AdministrationMiddleware;


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function() {
    Route::prefix('admin')
        ->as('admin.')
        ->middleware(AdministrationMiddleware::class)
        ->group(function () {
            Route::get('/', 'AdminController@index')->name('home');

            Route::resource('tours', 'TourController')->names('tours');

            Route::prefix('checkout')->as('checkout.')
                ->namespace('Checkout')->group(function () {
                    Route::resource('tours', 'TourController')->names('tours');
                    Route::resource('tours.forms', 'TourFormController')
                        ->except(['create', 'store', 'show'])->names('tours.forms');

                    Route::resource('souvenirs', 'SouvenirController')
                        ->except(['show'])->names('souvenirs');
                });

            Route::resource('users', 'UserController')->except(['show'])->names('users');

            Route::resource('options', 'OptionController')
                ->except(['show'])->names('options');

            Route::resource('module', 'ModuleController')
                ->only(['index', 'store'])->names('modules');

            Route::resource('media', 'MediaController')
                ->except(['show', 'update', 'create', 'edit'])->names('media');
            Route::post('ajax-media', 'MediaController@ajaxLoad')->name('ajax-media');

            Route::resource('souvenirs', 'SouvenirController')
                ->names('souvenirs');

            Route::resource('currencies', 'CurrencyController')
                ->only(['index', 'store'])
                ->names('currencies');
        });
});

Modules/Admin/Http/Controllers/Checkout/TourController.php
<?php

namespace Modules\Admin\Http\Controllers\Checkout;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Admin\Entities\Checkout;
use Modules\Admin\Http\Controllers\BaseController;
use Modules\Admin\Http\Requests\CheckoutTourRequest;
use Modules\Option\Entities\Option;
use RealRashid\SweetAlert\Facades\Alert;

class TourController extends BaseController
{
    /**
     * TourController constructor.
     */
    public function __construct()
    {
        $this->model = new Checkout;
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $list = $this->model->where('type', 'tour')->get()->sortByDesc('created_at');
        return view('admin::checkout.tour.index',
            compact('list')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = $this->model;
        $options = Option::all();

        return view('admin::checkout.tour.create',
            compact('item', 'options')
        );
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CheckoutTourRequest $request)
    {

        $user_id =(int) $request->user['id'];
        $this->model->fill(array_merge($request->all(), compact('user_id')));
        $this->model->save();

        $this->model->product()->create($request->product);

        $this->model->options()->createMany(collect($request->option)->map(function($item){
            return ($item['price'] and $item['quantity'] and $item['name'])?$item:null;
        })->filter()->toArray());

        $this->model->payment()->create($request->payment);

        $this->model->user->fill($request->user);

        $this->createUserForms($this->model, $request->product['q_ukraine'],  $request->product['q_other']);

        Alert::success('Добавление заказа', 'Успешно!');
        return redirect()->route('admin.checkout.tours.index');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $item = $this->model->find($id);

        return view('admin::checkout.tour.show',
            compact('item')
        );
    }

    /**
     * Show the form for editing the specified resource.
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->model->find($id);

        return view('admin::checkout.tour.edit',
            compact('item')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $item = $this->model->find($id);
        $this->createUserForms($item, $request->product['q_ukraine'],  $request->product['q_other']);

        $item->fill($request->all())->save();

        $item->user->fill($request->user)->save();

        $item->product->fill($request->product)->save();

        $item->options->map(function($option, $Num) use($request){
            $rOption = collect($request->option)->where('name', $option->name)->first();
            if($rOption['quantity'] and $rOption['price'])
                $option->fill($rOption)->save();
            else
                $option->delete();
        });

        $item->payment->fill($request->payment)->save();

        Alert::info('Обновление заказа', 'Успешно!');
        return redirect()->route('admin.checkout.tours.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $item = $this->model->find($id);
        if($item)
        $item->delete();

        Alert::success('Удаление заказа', 'Успешно!');
        return redirect()->back();
    }

    /**
     * Checker quantity user forms to access in Chernobyl
     * @param Checkout $model
     * @param int $quantity_ua
     * @param int $quantity_o
     */
    protected function createUserForms(Checkout $model,int $quantity_ua,int $quantity_o): void
    {
        $countForm =(int) $quantity_ua + $quantity_o;
        if($model->userForm->count() != $countForm) $model->userForm()->delete();

        if($model->userForm->isEmpty())
            for ($i = 0; $i < $countForm; $i++)
                $model->userForm()->create(['status' => 'unconfirmed']);

        # Пересобрал ибо нужно внести код
        $model->userForm()->get()->map(function ($uf) {
            $uf->share_code = base64_encode($uf->id . "|" . $uf->checkout_id);
            $uf->save();
        });
    }

}

Modules/Admin/Http/Controllers/TourController.php
<?php

namespace Modules\Admin\Http\Controllers;

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Modules\Admin\Http\Requests\TourRequest;
use Modules\Tour\Entities\Tour;
use RealRashid\SweetAlert\Facades\Alert;

class TourController extends BaseController
{
    /**
     * TourController constructor.
     */
    public function __construct()
    {
        $this->model = new Tour;
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $list = $this->model->all();

        return view('admin::tours.index',
            compact('list')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = $this->model->first();

        $item->data = $item->getDataByLocale()->groupBy('name')->map(function ($item) {
            $data = $item->first();
            $data->value = null;

            return $data;
        });

        $item->price = $item->price->groupBy('human')->map(function ($price) {
            return $price->groupBy('currency')->map(function ($pp) {
                $price = $pp->first();
                $price->value = null;

                return $price;
            });
        });

        $item->date = [$item->date->map(function ($item) {
            $item->start = $item->end = null;
            return $item;
        })->first()];

        return view('admin::tours.create',
            compact('item')
        );
    }

    /**
     * Store a newly created resource in storage.
     * @param TourRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TourRequest $request)
    {
        $slug = Str::slug($request->data['title']['value']);

        $item = $this->model->firstOrNew(compact('slug'));
        $item->save();
        $tour_id = $item->id;

        $data = collect($request->data)->map(function ($item, $name) use ($tour_id) {
            $value = $item['value'];
            return Tour\Data::where(compact('name'))->get()->map(function ($model) use ($value, $tour_id) {

                $model->value = $value;
                $model->tour_id = $tour_id;
                unset($model->id);

                return $model->toArray();
            });
        })->flatten(1);
        $item->data()->createMany($data);

        $prices = collect($request->price)->map(function ($price, $human) {
            return collect($price)->map(function ($item, $currency) use ($human) {
                $value = $item['value'];
                return compact('value', 'currency', 'human');
            });
        })->flatten(1);
        $item->price()->createMany($prices);

        $dates = collect($request->date)->map(function ($date) {
            if (isset($date['start']) and isset($date['end'])) return $date;
        })->filter()->toArray();
        $item->date()->createMany($dates);

        Alert::success('Тур', 'Успешно создан!');
        return redirect()->route('admin.tours.index');
    }


    /**
     * Show the form for editing the specified resource.
     * @param Tour $tour
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Tour $tour)
    {
        $item = $tour;

        $item->data = $item->getDataByLocale()->groupBy('name')->map(function ($item) {
            return $item->first();
        });

        $item->price = $item->price->groupBy('human')->map(function ($price) {
            return $price->groupBy('currency')->map(function ($pp) {
                return $pp->first();
            });
        });

        return view('admin::tours.edit',
            compact('item')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param TourRequest $request
     * @param Tour $tour
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TourRequest $request, Tour $tour)
    {
        $item = $tour;

        collect($request->data)->map(function ($field, $name) use ($item) {
            $value = $field['value'];
            $item->data->where('lang', '=', LocaleMiddleware::getLocale()?:LocaleMiddleware::$mainLanguage)->where('name', '=', $name)->first()
                ->fill(compact('value'))->save();
        });

        collect($request->price)->map(function ($field, $human) use ($item) {
            collect($field)->map(function ($field, $currency) use ($human, $item) {
                $price = $item->price->where('currency', $currency)->where('human', $human)->first();
                $price->value = $field['value'];
                $price->save();
            });
        });

        $item->date()->delete();
        $dates = collect($request->date)->map(function ($date) {
            return (isset($date['start']) and isset($date['end']))?$date:null;
        })->filter()->toArray();
        $item->date()->createMany($dates);

        Alert::success('Тур', "Успешно отредактирован");
        return redirect()->route('admin.tours.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param Tour $tour
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Tour $tour)
    {
        $item = $tour;
        $item->delete();

        Alert::info('Тур', "Запись успрешно удалена");
        return redirect()->route('admin.tours.index');
    }
}

Modules/Admin/Resources/views/tours/create.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">CREATE</div>
        <div class="card-body">

            {!! Form::model($item, ['route' => 'admin.tours.store', 'method' => 'POST']) !!}


            <div class="row">
                <div class="col-md-12 d-flex justify-content-end">
                    <button class="btn btn-primary">Добавить</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @include('admin::tours.includes.form')
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

Modules/Admin/Resources/views/tours/edit.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">CREATE</div>
        <div class="card-body">

            {!! Form::model($item, ['route' => ['admin.tours.update', $item->id], 'method' => 'PATCH']) !!}

            <div class="row">
                <div class="col-md-12 d-flex justify-content-end">

                    <a style="color:white" class="btn btn-secondary mr-2" onclick="location.href='{{ route("admin.users.index") }}'">Вернуться</a>
                    <button class="btn btn-primary">Обновить</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @include('admin::tours.includes.form')
                </div>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

Modules/Admin/Resources/views/tours/index.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-success"
                                    onclick="location.href='{{ route('admin.tours.create') }}'">
                                Создать
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Туры</div>
                <div class="card-body">
                    @if($list->isEmpty())
                        <div class="row">
                            <div class="col-md-12">
                                Здесь пусто....
                            </div>
                        </div>
                    @else
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-hover hover-pointer">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Название</th>
                                        <th>Цены</th>
                                        <th>Создан</th>
                                        <th>Действия</th>
                                    </tr>
                                    </thead>
                                    @foreach($list as $item)
                                        <tbody>
                                        <tr onclick='location.href="{{ route('admin.tours.edit', $item->id) }}"'>
                                            <td class="align-middle">
                                                <a href="{{ route('admin.tours.edit', $item->id) }}">
                                                    {{ $item->id }}
                                                </a>
                                            </td>
                                            <td class="align-middle">{{ $item->firstByName('title') }}</td>
                                            <td class="align-middle">
                                                USD: {{ $item->getPriceByCurrency('USD')->pluck('value')->implode('/') }}
                                                <br>
                                                UAH: {{ $item->getPriceByCurrency('UAH')->pluck('value')->implode('/') }}
                                                <br>
                                                EUR: {{ $item->getPriceByCurrency('EUR')->pluck('value')->implode('/') }}
                                            </td>
                                            <td class="align-middle">{{ $item->created_at->format('H:i d.m.Y') }}</td>
                                            <td class="d-flex justify-content-start align-middle">
                                                {!! Form::open(['route' => ['admin.tours.destroy', $item->id], 'method' => 'DELETE']) !!}
                                                <button class="btn btn-danger">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                        </tbody>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection