Modules/Admin/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Admin\Http\Middleware\AdministrationMiddleware;


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function() {
    Route::prefix('admin')
        ->as('admin.')
        ->middleware(AdministrationMiddleware::class)
        ->group(function () {
            Route::get('/', 'AdminController@index')->name('home');

            Route::resource('tours', 'TourController')->names('tours');

            Route::prefix('checkout')->as('checkout.')
                ->namespace('Checkout')->group(function () {
                    Route::resource('tours', 'TourController')->names('tours');
                    Route::resource('tours.forms', 'TourFormController')
                        ->except(['create', 'store', 'show'])->names('tours.forms');

                    Route::resource('souvenirs', 'SouvenirController')
                        ->except(['show'])->names('souvenirs');
                });

            Route::resource('users', 'UserController')->except(['show'])->names('users');

            Route::resource('options', 'OptionController')
                ->except(['show'])->names('options');

            Route::resource('module', 'ModuleController')
                ->only(['index', 'store'])->names('modules');

            Route::resource('media', 'MediaController')
                ->except(['show', 'update', 'create', 'edit'])->names('media');
            Route::post('ajax-media', 'MediaController@ajaxLoad')->name('ajax-media');

            Route::resource('souvenirs', 'SouvenirController')
                ->names('souvenirs');

            Route::resource('currencies', 'CurrencyController')
                ->only(['index', 'store'])
                ->names('currencies');
        });
});

Modules/Admin/Http/Controllers/UserController.php
<?php

namespace Modules\Admin\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Modules\Admin\Http\Requests\UserRequest;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends BaseController
{
    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->model = new User;
    }

    /**
     * Display a listing of the resource.
     * * @return \Illuminate\View\View
     */
    public function index()
    {
        $list = $this->model->where('id', '!=', auth()->id())->get();

        return view('admin::user.index',
            compact('list')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $item = $this->model;

        return view('admin::user.create',
            compact('item')
        );
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request)
    {
        $this->model->fill($request->all())->save();

        Alert::success('Пользователь', 'Успешно создан!!');
        return redirect()->route('admin.users.edit', $this->model->id);
    }


    /**
     * Show the form for editing the specified resource.
     * @param User $id
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('admin::user.edit',[
                'item' => $user
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, $id)
    {
        $item = $this->model->find($id);
        $all = $request->all();
        if(!$all['password']) unset($all['password']);
        else $all['password'] = Hash::make($all['password']);

        $item->fill($all)->save();

        Alert::success('Пользователь', 'Успешно отредаткированно!');
        return redirect()->route('admin.users.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $item = $this->model->find($id);
        $item->role = 'disabled';
        $item->save();

        Alert::info('Пользователь', 'Успешно блокирован!');
        return redirect()->route('admin.users.index');
    }
}

Modules/Admin/Resources/views/user/create.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">CREATE</div>
        <div class="card-body">

            {!! Form::model($item, ['route' => 'admin.users.store', 'method' => 'POST']) !!}


            <div class="row">
                <div class="col-md-12 d-flex justify-content-end">
                    <button class="btn btn-primary">Добавить</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @include('admin::user.includes.form')
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

Modules/Admin/Resources/views/user/edit.blade.php
@extends('admin::layouts.master')

@section('content')

    {!! Form::model($item, ['route' => ['admin.users.update', $item->id], 'method' => 'PATCH']) !!}
    {{ Form::hidden('id') }}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-md-12 d-flex justify-content-end">
                        <a style="color:white" class="btn btn-secondary mr-2"
                           onclick="location.href='{{ route("admin.users.index") }}'">Вернуться</a>
                        <button class="btn btn-primary">Обновить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">CREATE</div>
                <div class="card-body">
                    @include('admin::user.includes.form')
                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}
@endsection

Modules/Admin/Resources/views/user/index.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-success"
                                    onclick="location.href='{{ route('admin.users.create') }}'">
                                Создать
                            </button>
                        </div>
                    </div>
                </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Пользователи</div>
                <div class="card-body">
                    @if($list->isEmpty())
                        <div class="row">
                            <div class="col-md-12">
                                Здесь пусто....
                            </div>
                        </div>
                    @else
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-hover hover-pointer">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>ФИО</th>
                                        <th>Роль</th>
                                        <th>Создан</th>
                                        <th>Действия</th>
                                    </tr>
                                    </thead>
                                    @foreach($list as $item)
                                        <tbody>
                                        <tr onclick='location.href="{{ route('admin.users.edit', $item->id) }}"'>
                                            <td>
                                                <a href="{{ route('admin.users.edit', $item->id) }}">
                                                    {{ $item->id }}
                                                </a>
                                            </td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ __('admin.role.'.$item->role) }}</td>
                                            <td>{{ $item->created_at->format('H:i d.m.Y') }}</td>
                                            <td class="d-flex justify-content-start">
                                                {!! Form::open(['route' => ['admin.users.destroy', $item->id], 'method' => 'DELETE']) !!}
                                                    <button class="btn btn-danger">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                        </tbody>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection