Modules/Admin/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Modules\Admin\Http\Middleware\AdministrationMiddleware;


Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function() {
    Route::prefix('admin')
        ->as('admin.')
        ->middleware(AdministrationMiddleware::class)
        ->group(function () {
            Route::get('/', 'AdminController@index')->name('home');

            Route::resource('tours', 'TourController')->names('tours');

            Route::prefix('checkout')->as('checkout.')
                ->namespace('Checkout')->group(function () {
                    Route::resource('tours', 'TourController')->names('tours');
                    Route::resource('tours.forms', 'TourFormController')
                        ->except(['create', 'store', 'show'])->names('tours.forms');

                    Route::resource('souvenirs', 'SouvenirController')
                        ->except(['show'])->names('souvenirs');
                });

            Route::resource('users', 'UserController')->except(['show'])->names('users');

            Route::resource('options', 'OptionController')
                ->except(['show'])->names('options');

            Route::resource('module', 'ModuleController')
                ->only(['index', 'store'])->names('modules');

            Route::resource('media', 'MediaController')
                ->except(['show', 'update', 'create', 'edit'])->names('media');
            Route::post('ajax-media', 'MediaController@ajaxLoad')->name('ajax-media');

            Route::resource('souvenirs', 'SouvenirController')
                ->names('souvenirs');

            Route::resource('currencies', 'CurrencyController')
                ->only(['index', 'store'])
                ->names('currencies');
        });
});

Modules/Admin/Http/Controllers/Checkout/SouvenirController.php
<?php

namespace Modules\Admin\Http\Controllers\Checkout;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Admin\Entities\Checkout;
use Modules\Souvenir\Entities\Souvenir;
use RealRashid\SweetAlert\Facades\Alert;

class SouvenirController extends Controller
{
    public function __construct()
    {
        $this->model = new Checkout;
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $list = $this->model->where('type', 'souvenirs')
            ->get()->sortByDesc('created_at');

        return view('admin::checkout.souvenir.index',
            compact('list')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $item = $this->model;

        $souvenirs = Souvenir::all()->keyBy('slug')->map(function($item){
            return $item->getField('title')->value;
        });
        $total_price = 0;
        $item->souvenirs = collect()->add([])->add([])->add([])->add([])->add([]);

        return view('admin::checkout.souvenir.create',
            compact('item', 'souvenirs', 'total_price')
        );
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $user_id = $request->user['id'];
        $item = $this->model->fill(array_merge(compact('user_id'), $request->all()));
        $item->save();

        collect($request->souvenirs)
            ->map(function($s){
                    return ($s['slug'])?$s:null;
            })->filter()
            ->map(function($s) use($item){
                $item->souvenirs()->create($s);
            });

        $item->payment()->create($request->payment);

        Alert::success('Заказ', 'Успешно создан!');
        return redirect()->route('admin.checkout.souvenirs.edit', $item->id);
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $item = $this->model->find($id);
        $souvenirs = Souvenir::all()->keyBy('slug')->map(function($item){
            return $item->getField('title')->value;
        });
        $total_price = $item->souvenirs->map(function($item){
            return $item->quantity * $item->price;
        })->sum();

        return view('admin::checkout.souvenir.edit',
            compact('item', 'souvenirs', 'total_price')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $item = $this->model->find($id);
        $item->fill($request->all())->save();
        if(!$request->payment['method'] or !$item->payment){
            Alert::error('Ошибка', 'Ошибка механизма оплаты!');
            return redirect()->route('admin.checkout.souvenirs.edit', $item->id);
        }
        $item->payment->fill($request->payment)->save();
        $item->user->fill($request->user)->save();

        $res_s = collect($request->souvenirs)->map(function($souvenir) use($item){
            if(!$souvenir['slug']) return null;
            $item->souvenirs->where('slug', $souvenir['slug'])->first()->fill($souvenir)->save();
            return 1;
        })->filter();
        if($res_s->count() == 0){
            Alert::error('Ошибка', 'Нужно выбраьт хоть один товар');
            return redirect()->route('admin.checkout.souvenirs.edit', $item->id);
        }

        Alert::success('Заказ', 'Успешно отредактирован!');
        return redirect()->route('admin.checkout.souvenirs.edit', $item->id);
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Admin/Http/Controllers/SouvenirController.php
<?php

namespace Modules\Admin\Http\Controllers;

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Modules\Admin\Http\Requests\SouvenirRequest;
use Modules\Souvenir\Entities\Souvenir;
use RealRashid\SweetAlert\Facades\Alert;

class SouvenirController extends BaseController
{
    /**
     * SouvenirController constructor.
     */
    public function __construct()
    {
        $this->model = new Souvenir;
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $list = $this->model->paginate(15);

        return view('admin::souvenirs.index',
            compact('list')
        );
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = $this->getDemoData();

        return view('admin::souvenirs.create',
            compact('item')
        );
    }

    /**
     * @return Souvenir
     */
    private function getDemoData()
    {
        $item = $this->model->first();
        $collection_data = $item->fieldsByLocale();
        $item->img = $item->slug = null;
        $data = $collection_data->map(function ($item) {
            $item->value = $item->souvenir_id = null;
            return $item->replicate();
        })->keyBy('name');

        $demo = $item->replicate();
        $demo->data = $data;
        $demo->options = collect();

        return $demo;
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SouvenirRequest $request)
    {
        $all = $request->all();
        $all['slug'] = Str::slug($request->data['title']['value']);
        $item = $this->model->fill($all);
        $item->save();

        $options = collect(optional($all)['options'])->map(function($option){
            $selection = 0;
            if(isset($option['selection']))
                $selection = 1;
            $option['attr_name'] = Str::slug($option['attr_title']);
            $option['opti_name'] = Str::slug($option['opti_title']);
            return array_merge($option, compact('selection'));
        })->toArray();
        $item->options()->createMany($options);

        $price = $all['price'];
        $item->price()->create($price);

        $data = collect($all['data'])->map(function($item, $name){
            if(!isset($item['value'])) return null;
            $collection = [];
            foreach(config('app.locales') as $lang) {
                $demoData = $this->model->first()->getField($name, $lang);
                $demoData->value = $item['value'];
                $demoData->lang = $lang;
                $demoData->souvenir_id = null;
                $collection[] = $demoData;
            }
            return $collection;
        })->flatten()->toArray();

        $item->data()->createMany($data);

        Alert::success('Сувенир', 'Успешно создан!');
        return redirect()->route('admin.souvenirs.edit', $item->id);
    }

    /**
     * Show the form for editing the specified resource.
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->model->find($id);
        $item->data = $item->data->where('lang', LocaleMiddleware::getLocale()?:LocaleMiddleware::$mainLanguage)->keyBy('name');

        return view('admin::souvenirs.edit',
            compact('item')
        );
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SouvenirRequest $request, $id)
    {
        $item = $this->model->find($id)->fill($request->all());
        $item->save();

        collect($request->data)->map(function($data, $name) use($item){
            $item->data->where('name', $name)->where('lang', LocaleMiddleware::getLocale()?:LocaleMiddleware::$mainLanguage)->first()->fill($data)->save();
        });

        $item->price->fill($request->price)->save();

        $item->options()->delete();
        $options = collect($request->options)->map(function($option){
            $selection = 0;
            if(isset($option['selection']))
                $selection = 1;
            $option['attr_name'] = Str::slug($option['attr_title']);
            $option['opti_name'] = Str::slug($option['opti_title']);
            return array_merge($option, compact('selection'));
        })->toArray();
        $item->options()->createMany($options);

        Alert::success('Сувенир', 'Успешно отредактирован!');
        return redirect()->route('admin.souvenirs.edit', $item->id);
    }

    /**
     * Remove the specified resource from storage.
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $this->model->find($id)->delete();

        Alert::info('Сувенир', 'Успешно удален!');
        return redirect()->route('admin.souvenirs.index');
    }
}

Modules/Admin/Resources/views/souvenirs/create.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">CREATE</div>
        <div class="card-body">

            {!! Form::model($item, ['route' => 'admin.souvenirs.store', 'method' => 'POST']) !!}


            <div class="row">
                <div class="col-md-12 d-flex justify-content-end">
                    <button class="btn btn-primary">Добавить</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @include('admin::souvenirs.includes.form')
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

Modules/Admin/Resources/views/souvenirs/edit.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">CREATE</div>
        <div class="card-body">

            {!! Form::model($item, ['route' => ['admin.souvenirs.update', $item->id], 'method' => 'PATCH']) !!}

            <div class="row">
                <div class="col-md-12 d-flex justify-content-end">

                    <a style="color:white" class="btn btn-secondary mr-2" onclick="location.href='{{ route("admin.souvenirs.index") }}'">Вернуться</a>
                    <button class="btn btn-primary">Обновить</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @include('admin::souvenirs.includes.form')
                </div>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

Modules/Admin/Resources/views/souvenirs/index.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 d-flex justify-content-end">
                            <button class="btn btn-success"
                                    onclick="location.href='{{ route('admin.souvenirs.create') }}'">
                                Создать
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Сувениры</div>
                <div class="card-body">
                    @if($list->isEmpty())
                        <div class="row">
                            <div class="col-md-12">
                                Здесь пусто....
                            </div>
                        </div>
                    @else
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-hover hover-pointer">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Изображение</th>
                                        <th>Заголовок</th>
                                        <th>Цена</th>
                                        <th>Краткое описание</th>
                                        <th>Действия</th>
                                    </tr>
                                    </thead>
                                    @foreach($list as $item)
                                        <tbody>
                                        <tr onclick='location.href="{{ route('admin.souvenirs.edit', $item->id) }}"'>
                                            <td>
                                                <a href="{{ route('admin.souvenirs.edit', $item->id) }}">
                                                    {{ $item->id }}
                                                </a>
                                            </td>
                                            <td>
                                                <div style="max-width: 100px; max-height: 150px">
                                                    <img src="{{ optional($item->media)->src?:"/not-found-photo.jpg" }}" class="w-100 h-auto" style="max-height: 150px">
                                                </div>
                                            </td>
                                            <td>{{ $item->getField('title')->value }}</td>
                                            <td>{{ $item->priceWithCurrency() }}</td>
                                            <td>
                                                {{ Str::words($item->getField('description')->value, 20) }}
                                            </td>
                                            <td class="d-flex justify-content-start">
                                                {!! Form::open(['route' => ['admin.souvenirs.destroy', $item->id], 'method' => 'DELETE']) !!}
                                                    <button class="btn btn-danger">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                        </tbody>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                {{ $list->links() }}
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection